name: snakemake
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp
  - aiohttp
  - aiosignal
  - amply
  - anyio
  - appdirs
  - argon2-cffi
  - argon2-cffi-bindings
  - argparse-dataclass
  - arrow
  - asttokens
  - attmap
  - attrs
  - beautifulsoup4
  - black
  - bleach
  - blosc
  - boto
  - boto3
  - botocore
  - branca
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cached-property
  - cached_property
  - cachetools
  - cairo
  - certifi
  - cffi
  - cfitsio
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - colorama
  - comm
  - conda-inject
  - configargparse
  - connection_pool
  - contourpy
  - cryptography
  - cycler
  - datrie
  - debugpy
  - decorator
  - defusedxml
  - docutils
  - dpath
  - eido
  - entrypoints
  - exceptiongroup
  - executing
  - expat
  - fiona
  - folium
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - fqdn
  - freetype
  - freexl
  - fribidi
  - frozenlist
  - gdal
  - geopandas
  - geopandas-base
  - geos
  - geotiff
  - gettext
  - gitdb
  - gitpython
  - glpk
  - google-api-core
  - google-auth
  - google-cloud-core
  - google-cloud-storage
  - google-crc32c
  - google-resumable-media
  - googleapis-common-protos
  - graphite2
  - graphviz
  - grpc-cpp
  - grpcio
  - gtest
  - gts
  - harfbuzz
  - hdf4
  - hdf5
  - humanfriendly
  - icu
  - idna
  - immutables
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - iniconfig
  - intel-openmp
  - ipykernel
  - ipython
  - isoduration
  - isort
  - jedi
  - jinja2
  - jmespath
  - joblib
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jsonschema-with-format-nongpl
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab_code_formatter
  - jupyterlab_pygments
  - kealib
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libaec
  - libarchive
  - libblas
  - libboost-headers
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcrc32c
  - libcurl
  - libdeflate
  - libexpat
  - libffi
  - libgd
  - libgdal
  - libglib
  - libhwloc
  - libiconv
  - libjpeg-turbo
  - libkml
  - liblapack
  - libnetcdf
  - libpng
  - libpq
  - libprotobuf
  - librttopo
  - libsodium
  - libspatialindex
  - libspatialite
  - libsqlite
  - libssh2
  - libtiff
  - libwebp
  - libwebp-base
  - libxcb
  - libxml2
  - libzip
  - libzlib
  - logmuse
  - lz4-c
  - lzo
  - mapclassify
  - markdown-it-py
  - markupsafe
  - matplotlib-base
  - matplotlib-inline
  - mdurl
  - minizip
  - mistune
  - mkl
  - multidict
  - munkres
  - mypy_extensions
  - nbclient
  - nbconvert-core
  - nbformat
  - nest-asyncio
  - networkx
  - numpy
  - openjpeg
  - openssl
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - pango
  - parso
  - pathspec
  - patsy
  - pcre2
  - peppy
  - pickleshare
  - pillow
  - pip
  - pixman
  - pkgutil-resolve-name
  - plac
  - platformdirs
  - pluggy
  - poppler
  - poppler-data
  - postgresql
  - proj
  - prometheus_client
  - prompt-toolkit
  - protobuf
  - psutil
  - pthread-stubs
  - pulp
  - pure_eval
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyproj
  - pysocks
  - pytest
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-tzdata
  - python_abi
  - pytz
  - pywin32
  - pyyaml
  - pyzmq
  - re2
  - referencing
  - requests
  - reretry
  - rfc3339-validator
  - rfc3986-validator
  - rich
  - rpds-py
  - rsa
  - rtree
  - s3transfer
  - scikit-learn
  - scipy
  - seaborn
  - seaborn-base
  - send2trash
  - setuptools
  - shapely
  - six
  - slack-sdk
  - slack_sdk
  - smart_open
  - smmap
  - snakemake-interface-common
  - snakemake-interface-report-plugins
  - snakemake-interface-storage-plugins
  - snappy
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - statsmodels
  - stopit
  - tabulate
  - tbb
  - terminado
  - threadpoolctl
  - throttler
  - tiledb
  - tinycss2
  - tk
  - tomli
  - toposort
  - tornado
  - tqdm
  - traitlets
  - types-python-dateutil
  - typing-extensions
  - typing_extensions
  - typing_utils
  - tzdata
  - ubiquerg
  - uri-template
  - uriparser
  - urllib3
  - veracitools
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - wheel
  - wrapt
  - xarray
  - xerces-c
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxpm
  - xorg-libxt
  - xorg-xextproto
  - xorg-xproto
  - xyzservices
  - xz
  - yaml
  - yarl
  - yte
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
      - snakemake
      - snakemake-interface-executor-plugins
