paths:
  #gams: /fp/projects01/ec85/.bin/gams/gams41.5_linux_x64_64_sfx/
  gams: C:/GAMS/
  #shared_input: /fp/projects01/ec85/models/max/special_issue/shared_input/
  shared_input: shared_input/
  #abs_shared_code: /fp/projects01/ec85/models/group/joint_wind/highRES-model/resources/4_model_code_shared/
  abs_shared_code: ../../../../resources/4_model_code_shared
  #abs_con: /cluster/work/projects/ec85/joint-wind/koenandaleksera5/
  abs_con: resources/bias/
  #resultsdir: /cluster/work/projects/ec85/joint-wind/model-aggregated/resultscosts/
  resultsdir: results
